//Author registration route
###
POST http://localhost:3000/restaurantapi/owner
Content-Type: application/json

{
    "userType":"restaurant",
    "username":"adharsh1",
    "password":"adharsh1",
    "email":"adharsh1@gmail.com",
    "restaurantname":"pistahouse",
    "location":"KPHB"
}

###
//Author login route
POST http://localhost:3000/restaurantapi/login
Content-Type: application/json

{
    "userType":"restaurant",
    "username":"adharsh1",
    "password":"adharsh1"
}

###
//Adding menu-item by restaurant
POST http://localhost:3000/restaurantapi/menu
Content-Type: application/json

{
    "image":"https://spicecravings.com/wp-content/uploads/2020/10/Egg-Biryani-Featured-1.jpg",
    "title":"Egg Biryani",
    "category":"Biryani",
    "price":"500",
    "restaurantname":"pistahouse"
}

###
//Getting menu items by restaurant name
GET http://localhost:3000/restaurantapi/menu/pistahouse
