POST http://localhost:3000/userapi/user
Content-Type: application/json

{
    "userType":"user",
    "username":"ravi",
    "password":"ravi",
    "email":"ravi@gmail.com"
}

//post request for user login
###
POST http://localhost:3000/userapi/login
Content-Type: application/json

{
    "userType":"user",
    "username":"ravi",
    "password":"ravi"
}

###
//getting menus from all restaurants
GET http://localhost:3000/userapi/menu